name: CI-Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  must:
    runs-on: ubuntu-latest
    env:
      FAKE_SECRET_TOKEN: e8a0f0e943356ec73995bdefb8dbf3a75fdce4323effbfbe3f1a2a809f65eba57ce7ce8c
      DEPLOY_ENV: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Echo Fake Token
      run: echo "Using token: $FAKE_SECRET_TOKEN"

    - name: Deploy to staging
      run: echo "Deploying to staging with token $FAKE_SECRET_TOKEN"
